import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'fr';
  static const String _langKey = 'selected_language';
  
  String get currentLanguage => _currentLanguage;
  
  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_langKey) ?? 'fr';
    notifyListeners();
  }
  
  // Obtenir le nom de la langue affichée
  String get languageName {
    switch (_currentLanguage) {
      case 'fr':
        return 'Français';
      case 'en':
        return 'English';
      case 'es':
        return 'Español';
      default:
        return 'Français';
    }
  }
  
  Future<void> setLanguage(String languageCode) async {
    _currentLanguage = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_langKey, languageCode);
    notifyListeners();
  }
  
  // Méthode pour obtenir une traduction
  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['fr']?[key] ?? key;
  }
  
  // Traductions
  static final Map<String, Map<String, String>> _translations = {
    'fr': {
      // Général
      'hello': 'Bonjour',
      'back': 'Retour',
      'continue': 'Continuer',
      'apply': 'Appliquer',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'add': 'Ajouter',
      'edit': 'Modifier',
      'search': 'Rechercher',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      
      // Navigation
      'home': 'Accueil',
      'missions': 'Missions',
      'training': 'Formations',
      'profile': 'Profil',
      
      // Login
      'login': 'Connexion',
      'email': 'Email',
      'password': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'no_account': 'Pas encore de compte ?',
      'register': 'S\'inscrire',
      'register_link': 'Inscrivez-vous.',
      'login_instructions': 'Entrez votre email et mot de passe pour accéder à votre compte.',
      'error_password_short': 'Le mot de passe doit contenir au moins 6 caractères',
      'test_mode': 'Mode Test',
      'choose_account_type': 'Choisissez le type de compte à tester :',
      'professional': 'Professionnel',
      'client_establishment': 'Client (Établissement)',
      'admin': 'Admin',
      'get_started': 'Commencer',
      'already_have_account': 'Vous avez déjà un compte ?',
      'forgot_password_desc': 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
      'email_sent_title': 'Email envoyé !',
      'email_sent_desc1': 'Nous avons envoyé un lien de réinitialisation à',
      'email_sent_desc2': 'Vérifiez votre boîte de réception et suivez les instructions pour réinitialiser votre mot de passe.',
      'send_link': 'Envoyer le lien',
      'back_to_login': 'Retour à la connexion',
      'resend_email': 'Renvoyer l\'email',
      'registration': 'Inscription',
      'choose_profile': 'Choisissez Votre Profil',
      'choose_profile_desc': 'Pour Vous Offrir Une Expérience Personnalisée, Veuillez Nous Indiquer Votre Profil',
      'student_profile': 'Étudiant (Travailleur)',
      'student_profile_desc': 'Je Recherche Une Formation, Une Alternance, Un Emploi Étudiant Ou Un Premier Emploi.',
      'recruiter_profile': 'Recruteur (Structure)',
      'recruiter_profile_desc': 'Je Souhaite Recruter Des Stagiaires, Alternants, Ou Jeunes Diplômés Pour Ma Structure.',
      'who_are_you': 'Commencez par nous dire qui vous êtes ?',
      'who_are_you_desc': 'Ces informations nous aideront à mieux vous connaître et à créer votre compte.',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'full_address': 'Adresse Complète',
      'phone_number': 'Numéro de téléphone',
      'next': 'SUIVANT',
      'login_back': 'Connexion',
      'documents_title': 'Vos documents pour valider votre profil',
      'documents_subtitle': 'Nous avons besoin de quelques pièces pour confirmer votre identité et vos qualifications.',
      'id_card': 'Carte d\'identité *',
      'cv': 'Curriculum Vitae(CV) *',
      'diplomas': 'Diplome (s):',
      'no_file': 'Aucun fichier',
      'error_file_pick': 'Erreur lors de la sélection du fichier:',
      'journey_title': 'Parlez-nous de votre parcours',
      'journey_subtitle': 'Avez-vous déjà travaillé en cuisine ou dans une structure de santé ? Dites-nous tout.',
      'add_experience': 'Ajoutez une expérience',
      'register_submit': 'S\'INSCRIRE',
      'professional_experience': 'Expérience Professionnelle',
      'experience_hint': 'Ex: Cuisinier à iTea',
      'start_date': 'Date Début',
      'end_date': 'Date Fin',
      'select_year_month': 'Sélectionner l\'année et le mois',
      'january': 'Janvier', 'february': 'Février', 'march': 'Mars', 'april': 'Avril',
      'may': 'Mai', 'june': 'Juin', 'july': 'Juillet', 'august': 'Août',
      'september': 'Septembre', 'october': 'Octobre', 'november': 'Novembre', 'december': 'Décembre',
      
      // Home
      'mission_of_day': 'Mission du jour',
      'upcoming_missions': 'Missions à venir',
      'quick_access': 'Accès rapides',
      'access_mission': 'Accéder à la mission',
      'incidents': 'Incidents',
      'in_progress': 'En cours',
      
      // Missions
      'upcoming': 'À venir',
      'completed': 'Terminées',
      'pending': 'En attente',
      'confirmed': 'Confirmé',
      'refused': 'Refusé',
      'end_mission': 'Terminer la mission',
      'report_incident': 'Signaler un incident',
      
      // Mission Detail
      'access_logistics': 'Accès & Logistique',
      'entry_code': 'Code entrée',
      'kitchen_code': 'Code cuisine',
      'call_contact': 'Appeler le contact',
      'menu_of_day': 'Menu du jour',
      'see_recipe': 'Voir la recette',
      'calculated_quantities': 'Quantités calculées',
      'residents': 'résidents',
      'daily_checklist': 'Checklist journée',
      
      // Training
      'mandatory': 'Obligatoires',
      'recommended': 'Recommandées',
      'duration': 'Durée',
      'completed_status': 'Terminé',
      'to_do': 'À faire',
      
      // Profile
      'documents': 'Documents',
      'add_document': 'Ajouter un document',
      'settings': 'Paramètres',
      'logout': 'Se déconnecter',
       'cv': 'Curriculum Vitae(CV)',
      'id_card': 'Carte d\'identité',
      'diploma': 'Diplôme cuisine',
      'cook_diploma': 'Diplôme de cuisine',
      'professional_cook': 'Cuisinier professionnel',
      'doc_added': 'Document ajouté',
      'doc_error': 'Erreur lors de l\'ajout du document',
      'doc_opening': 'Ouverture de',

      // Home & Dashboard
      'mission_today': 'Mission aujourd\'hui',
      'available_professionals': 'Professionnels disponibles',
      'active_sites': 'Sites actifs',
      'create_mission': 'Créer mission',
      'create_training': 'Créer formation',
      'missions_of_day': 'Missions du jour',
      'see_all': 'Voir tout',
      'no_mission_available': 'Aucune mission disponible',
      'all_missions': 'Toutes les missions',
      'recent_alerts': 'Alertes récentes',
      'incident_reported': 'Incident signalé',
      'new_note': 'Nouvelle note',
      'trainings_to_validate': 'formations à valider',
      'mission_management': 'Gestion des Missions',
      'team_management': 'Gestion de l\'équipe',
      'my_profile': 'Mon Profil',
      'full_name': 'Nom complet',
      'role': 'Rôle',
      'admin_role': 'Administrateur',
      'directrice_role': 'Directrice',
      'chef_role': 'Chef de cuisine',
      'residents_stat': 'Résidents',
      'chefs_stat': 'Chefs',
      'information': 'Informations',
      'address_label': 'Adresse',
      'phone_label': 'Téléphone',
      'capacity': 'Capacité',
      'residents_count': 'résidents',
      'actions': 'Actions',
      'send_feedback': 'Envoyer un retour',
      'report_incident_btn': 'Signaler un incident',
      'your_satisfaction': 'Votre satisfaction',
      'your_comment': 'Votre commentaire',
      'send_feedback_btn': 'Envoyer le retour',
      'today_label': 'Aujourd\'hui',
      'tomorrow_label': 'Demain',
      'planned': 'Planifiée',
      'starter': 'Entrée',
      'main_course': 'Plat',
      'side_dish': 'Accompagnant',
      'dessert': 'Dessert',
      'menu_upper': 'MENU',
      'see_details': 'Voir les détails',
      'edit_info': 'Modifier les informations',
      'change_password': 'Changer le mot de passe',
      
      // Search & Filters
      'search_mission_hint': 'Rechercher une mission...',
      'search_professional_hint': 'Rechercher un professionnel...',
      'search_no_results': 'Recherche non trouvée',
      'search_no_results_desc': 'Aucune mission ne correspond à votre recherche',
      'no_professional_found': 'Aucun professionnel trouvé',
      'filters': 'Filtres',
      'today': 'Aujourd\'hui',
      'this_week': 'Cette semaine',
      'all_filter': 'Tous',

      // Actions & Dialogs
      'delete_mission_title': 'Supprimer la mission',
      'delete_mission_confirm': 'Êtes-vous sûr de vouloir supprimer cette mission ?',
      'mission_deleted': 'Mission supprimée',
      'mission_label': 'Mission :',
      'available': 'Disponibles',
      
      // Settings
      'language': 'Langue',
      'about': 'À propos de ARS',
      'privacy': 'Politique de confidentialité',
      'help_support': 'Aide & Support',
      'share_app': 'Partager l\'application',
      'language_changed': 'Langue changée en',
      
      // Registration Steps
      'step': 'Étape',
      'personal_info': 'Informations personnelles',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'phone': 'Téléphone',
      'date_of_birth': 'Date de naissance',
      'address': 'Adresse',
      'postal_code': 'Code postal',
      'city': 'Ville',
      'professional_experience': 'Expérience professionnelle',
      'main_function': 'Fonction principale',
      'years_experience': 'Années d\'expérience',
      'specialties': 'Spécialités',
      'select_function': 'Sélectionnez votre fonction',
      'select_experience': 'Sélectionnez',
      'required_documents': 'Documents requis',
      'profile_photo': 'Photo de profil',
      'cooking_diplomas': 'Diplômes de cuisine',
      'medical_certificate': 'Certificat médical',
      'driving_license': 'Permis de conduire',
      'create_password': 'Créer un mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'accept_terms': 'J\'accepte les conditions d\'utilisation',
      
      // Specialties
      'french_cuisine': 'Cuisine française',
      'italian_cuisine': 'Cuisine italienne',
      'asian_cuisine': 'Cuisine asiatique',
      'pastry': 'Pâtisserie',
      'vegetarian': 'Cuisine végétarienne',
      'collective': 'Cuisine collective',
      'no_missions': 'Aucune mission',
      'see_mission': 'Voir la mission',
      'confirm': 'Confirmer',
      'refuse': 'Refuser',
      'onboarding1_title': 'Rejoignez ARS.',
      'onboarding1_subtitle': 'Une communauté engagée pour améliorer les repas en milieu de santé.',
      'onboarding2_title': 'Formez-Vous',
      'onboarding2_subtitle': 'Formez-vous à votre rythme et soyez prêt pour vos missions.',
      'onboarding3_title': 'Soyez payés',
      'onboarding3_subtitle': 'Travail accompli, heures validées, paiement assuré.',
      'agency_name': 'Agence de Restauration & Santé',
      'faq_title': 'FAQ',
      'faq_subtitle': 'Trouvez des réponses à vos questions fréquentes',
      'contact_title': 'Contactez-nous',
      'contact_subtitle': 'Une question ? Notre équipe est là pour vous aider',
      'email_support_title': 'Support par Email',
      'email_support_subtitle': 'Envoyez-nous un message à tout moment',
      'phone_support_title': 'Support Téléphonique',
      'phone_support_subtitle': 'Appelez notre ligne d\'assistance dédiée',
      'help_center': 'Centre d\'Aide',
      'full_name': 'Nom complet',
      'name_hint': 'Entrez votre nom',
      'email_hint': 'Entrez votre email',
      'subject': 'Sujet',
      'subject_hint': 'Objet de votre message',
      'message': 'Message',
      'message_hint': 'Décrivez votre demande en détail...',
      'send_message': 'Envoyer le message',
      'category': 'Catégorie',
      'gen_question': 'Question générale',
      'tech_prob': 'Problème technique',
      'billing': 'Facturation',
      'other': 'Autre',
      'message_sent': 'Message envoyé avec succès !',
      'fill_form': 'Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.',
      'error_name': 'Veuillez entrer votre nom',
      'error_email': 'Veuillez entrer votre email',
      'error_email_invalid': 'Email invalide',
      'error_subject': 'Veuillez entrer un sujet',
      'error_message': 'Veuillez entrer votre message',
      'faq_q1': 'Comment accepter une mission ?',
      'faq_a1': 'Pour accepter une mission, rendez-vous dans l\'onglet "Missions", consultez les missions disponibles et cliquez sur celle qui vous intéresse. Vous pourrez ensuite voir les détails et cliquer sur "Accepter la mission".',
      'faq_q2': 'Comment modifier mes informations personnelles ?',
      'faq_a2': 'Allez dans l\'onglet "Profil", puis cliquez sur "Paramètres". Vous pourrez y modifier vos informations personnelles, vos documents et vos préférences.',
      'faq_q3': 'Que faire en cas de problème lors d\'une mission ?',
      'faq_a3': 'En cas de problème, utilisez le bouton "Signaler un incident" disponible sur la page de détail de votre mission en cours. Notre équipe sera alertée et vous contactera rapidement.',
      'faq_q4': 'Comment sont calculées mes heures de travail ?',
      'faq_a4': 'Vos heures de travail sont calculées automatiquement à partir de l\'heure de début et de fin de mission indiquées. Vous pouvez consulter votre historique dans l\'onglet "Missions terminées".',
      'faq_q5': 'Comment ajouter un nouveau document ?',
      'faq_a5': 'Dans l\'onglet "Profil", section "Documents", cliquez sur "+ Ajouter un document". Sélectionnez le fichier depuis votre appareil (formats acceptés : PDF, JPG, PNG).',
      'faq_q6': 'Comment changer la langue de l\'application ?',
      'faq_a6': 'Allez dans "Profil" > "Paramètres" > "Langue". Sélectionnez votre langue préférée parmi Français, Anglais ou Espagnol, puis cliquez sur "Appliquer".',
      
      // Admin specific
      'our_mission': 'Notre Mission',
      'mission_content': 'La mission d\'ARS est d\'assurer la préparation, l\'organisation et l\'exécution des services de restauration au sein des établissements partenaires, en respectant strictement les normes d\'hygiène, de sécurité et de qualité.',
      'legal_mentions': 'Mentions Légales',
      'legal_content': 'Les missions réalisées au sein de la plateforme ARS sont conformes aux obligations légales en vigueur (HACCP, sécurité alimentaire).',
      'data_collection': 'Collecte des données',
      'data_collection_content': 'Nous collectons uniquement les données nécessaires au bon fonctionnement de nos services (Identification, Coordonnées, Missions).',
      'data_usage': 'Utilisation des données',
      'data_usage_content': 'Vos données sont utilisées pour assurer la gestion des missions, améliorer nos services et respecter nos obligations légales.',
      'data_protection': 'Protection des données',
      'data_protection_content': 'Nous mettons en œuvre des mesures de sécurité appropriées (Chiffrement, Accès restreint, Sauvegardes).',
      'your_rights': 'Vos droits',
      'your_rights_content': 'Conformément au RGPD, vous disposez des droits d\'accès, de rectification, d\'effacement et d\'opposition.',
      'share_message': 'Découvrez ARS App - L\'application pour les professionnels de la restauration !\n\nRejoignez notre communauté de cuisiniers professionnels !',
      'share_subject': 'ARS App - Application pour professionnels de la restauration',
      'administration': 'Administration',
      'manage_resources': 'Gérer les ressources de la plateforme',
      'monthly_stats': 'Statistiques du mois',
      'pros_active': 'Pros actifs',
      'satisfaction': 'Satisfaction',
      'prof_management': 'Gestion professionnels',
      'sites_management': 'Gestion sites',
      'menus_management': 'Gestion menus',
      'recipes_management': 'Gestion recettes',
      'trainings_management': 'Gestion formations',
      'team': 'Équipe',
      'see': 'Voir',
      'schedule': 'Horaire',
      'date': 'Date',
      'all_filter': 'Tous',
      'confirm_delete_mission': 'Êtes-vous sûr de vouloir supprimer cette mission chez',
      'modify_info': 'Modifier les informations',
      'choose_profile_start': 'Choisissez votre profil pour commencer',
      'professional_subtitle': 'Cuisinier – Chef – Agent',
      'professional_desc': 'Je cherche des missions en cuisine',
      'client_subtitle': 'EHPAD – Clinique – Restaurant',
      'client_desc': 'Je cherche des professionnels qualifiés',
      'your_establishment': 'Votre Établissement',
      'establishment_info': 'Informations de votre établissement',
      'establishment_name': 'Nom de l\'établissement *',
      'establishment_type': 'Type d\'établissement *',
      'select_type': 'Sélectionnez un type',
      'full_address_required': 'Adresse complète *',
      'postal_code_required': 'Code postal *',
      'city_required': 'Ville *',
      'phone_required': 'Téléphone *',
      'capacity_required': 'Capacité *',
      'field_required': 'Ce champ est obligatoire',
      'visible_to_pros': 'Ces informations seront visibles par les professionnels de santé',
      'french_lang': 'Français',
      'english_lang': 'Anglais',
      'spanish_lang': 'Espagnol',
      'error_password': 'Veuillez entrer votre mot de passe',
      'step_count': 'Étape',
    },
    'en': {
      // General
      'hello': 'Hello',
      'back': 'Back',
      'continue': 'Continue',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'add': 'Add',
      'edit': 'Edit',
      'search': 'Search',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      
      // Navigation
      'home': 'Home',
      'missions': 'Missions',
      'training': 'Training',
      'profile': 'Profile',
      
      // Login
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'no_account': 'No account yet?',
      'register': 'Register',
      'register_link': 'Sign up.',
      'login_instructions': 'Enter your email and password to access your account.',
      'error_password_short': 'Password must be at least 6 characters long',
      'test_mode': 'Test Mode',
      'choose_account_type': 'Choose account type to test:',
      'professional': 'Professional',
      'client_establishment': 'Client (Establishment)',
      'admin': 'Admin',
      'get_started': 'Get Started',
      'already_have_account': 'Already have an account?',
      'forgot_password_desc': 'Enter your email address and we will send you a link to reset your password.',
      'email_sent_title': 'Email sent!',
      'email_sent_desc1': 'We have sent a reset link to',
      'email_sent_desc2': 'Check your inbox and follow the instructions to reset your password.',
      'send_link': 'Send link',
      'back_to_login': 'Back to login',
      'resend_email': 'Resend email',
      'registration': 'Registration',
      'choose_profile': 'Choose Your Profile',
      'choose_profile_desc': 'To Offer You A Personalized Experience, Please Indicate Your Profile',
      'student_profile': 'Student (Worker)',
      'student_profile_desc': 'I Am Looking For Training, Apprenticeship, Student Job Or A First Job.',
      'recruiter_profile': 'Recruiter (Structure)',
      'recruiter_profile_desc': 'I Wish To Recruit Interns, Apprentices, Or Young Graduates For My Structure.',
      'who_are_you': 'Start by telling us who you are?',
      'who_are_you_desc': 'This information will help us know you better and create your account.',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'full_address': 'Full Address',
      'phone_number': 'Phone Number',
      'next': 'NEXT',
      'login_back': 'Login',
      'documents_title': 'Your documents to validate your profile',
      'documents_subtitle': 'We need a few pieces to confirm your identity and qualifications.',
      'id_card': 'Identity card *',
      'cv': 'Curriculum Vitae (CV) *',
      'diplomas': 'Diploma(s):',
      'no_file': 'No file',
      'error_file_pick': 'Error while picking file:',
      'journey_title': 'Tell us about your background',
      'journey_subtitle': 'Have you ever worked in a kitchen or a healthcare facility? Tell us everything.',
      'add_experience': 'Add an experience',
      'register_submit': 'REGISTER',
      'professional_experience': 'Professional Experience',
      'experience_hint': 'Ex: Cook at iTea',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'select_year_month': 'Select year and month',
      'january': 'January', 'february': 'February', 'march': 'March', 'april': 'April',
      'may': 'May', 'june': 'June', 'july': 'July', 'august': 'August',
      'september': 'September', 'october': 'October', 'november': 'November', 'december': 'December',
      
      // Home
      'mission_of_day': 'Mission of the day',
      'upcoming_missions': 'Upcoming missions',
      'quick_access': 'Quick access',
      'access_mission': 'Access mission',
      'incidents': 'Incidents',
      'in_progress': 'In progress',
      
      // Missions
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'refused': 'Refused',
      'end_mission': 'End mission',
      'report_incident': 'Report incident',
      
      // Mission Detail
      'access_logistics': 'Access & Logistics',
      'entry_code': 'Entry code',
      'kitchen_code': 'Kitchen code',
      'call_contact': 'Call contact',
      'menu_of_day': 'Menu of the day',
      'see_recipe': 'See recipe',
      'calculated_quantities': 'Calculated quantities',
      'residents': 'residents',
      'daily_checklist': 'Daily checklist',
      
      // Training
      'mandatory': 'Mandatory',
      'recommended': 'Recommended',
      'duration': 'Duration',
      'completed_status': 'Completed',
      'to_do': 'To do',
      
      // Profile
      'documents': 'Documents',
      'add_document': 'Add a document',
      'settings': 'Settings',
      'logout': 'Logout',
       'cv': 'Curriculum Vitae(CV)',
      'id_card': 'ID Card',
      'diploma': 'Cooking Diploma',
      'cook_diploma': 'Cooking Diploma',
      'professional_cook': 'Professional Cook',
      'doc_added': 'Document added',
      'doc_error': 'Error adding document',
      'doc_opening': 'Opening',

      // Home & Dashboard
      'mission_today': 'Mission today',
      'available_professionals': 'Available professionals',
      'active_sites': 'Active sites',
      'create_mission': 'Create mission',
      'create_training': 'Create training',
      'missions_of_day': 'Missions of the day',
      'see_all': 'See all',
      'no_mission_available': 'No mission available',
      'all_missions': 'All missions',
      'recent_alerts': 'Recent alerts',
      'incident_reported': 'Incident reported',
      'new_note': 'New note',
      'trainings_to_validate': 'trainings to validate',
      'mission_management': 'Mission Management',
      'team_management': 'Team Management',
      'my_profile': 'My Profile',
      'full_name': 'Full name',
      'role': 'Role',
      'admin_role': 'Administrator',
      'directrice_role': 'Director',
      'chef_role': 'Head Chef',
      'residents_stat': 'Residents',
      'chefs_stat': 'Chefs',
      'information': 'Information',
      'address_label': 'Address',
      'phone_label': 'Phone',
      'capacity': 'Capacity',
      'residents_count': 'residents',
      'actions': 'Actions',
      'send_feedback': 'Send feedback',
      'report_incident_btn': 'Report an incident',
      'your_satisfaction': 'Your satisfaction',
      'your_comment': 'Your comment',
      'send_feedback_btn': 'Send feedback',
      'today_label': 'Today',
      'tomorrow_label': 'Tomorrow',
      'planned': 'Planned',
      'starter': 'Starter',
      'main_course': 'Main Course',
      'side_dish': 'Side Dish',
      'dessert': 'Dessert',
      'menu_upper': 'MENU',
      'see_details': 'See details',
      'edit_info': 'Edit Information',
      'change_password': 'Change password',
      
      // Search & Filters
      'search_mission_hint': 'Search a mission...',
      'search_professional_hint': 'Search a professional...',
      'search_no_results': 'Search not found',
      'search_no_results_desc': 'No mission matches your search',
      'no_professional_found': 'No professional found',
      'filters': 'Filters',
      'today': 'Today',
      'this_week': 'This week',
      'all_filter': 'All',

      // Actions & Dialogs
      'delete_mission_title': 'Delete mission',
      'delete_mission_confirm': 'Are you sure you want to delete this mission?',
      'mission_deleted': 'Mission deleted',
      'mission_label': 'Mission:',
      'available': 'Available',
      
      // Settings
      'language': 'Language',
      'about': 'About ARS',
      'privacy': 'Privacy Policy',
      'help_support': 'Help & Support',
      'share_app': 'Share app',
      'language_changed': 'Language changed to',
      
      // Registration Steps
      'step': 'Step',
      'personal_info': 'Personal information',
      'first_name': 'First name',
      'last_name': 'Last name',
      'phone': 'Phone',
      'date_of_birth': 'Date of birth',
      'address': 'Address',
      'postal_code': 'Postal code',
      'city': 'City',
      'professional_experience': 'Professional experience',
      'main_function': 'Main function',
      'years_experience': 'Years of experience',
      'specialties': 'Specialties',
      'select_function': 'Select your function',
      'select_experience': 'Select',
      'required_documents': 'Required documents',
      'profile_photo': 'Profile photo',
      'cooking_diplomas': 'Cooking diplomas',
      'medical_certificate': 'Medical certificate',
      'driving_license': 'Driving license',
      'create_password': 'Create password',
      'confirm_password': 'Confirm password',
      'accept_terms': 'I accept the terms and conditions',
      
      // Specialties
      'french_cuisine': 'French cuisine',
      'italian_cuisine': 'Italian cuisine',
      'asian_cuisine': 'Asian cuisine',
      'pastry': 'Pastry',
      'vegetarian': 'Vegetarian cuisine',
      'collective': 'Collective catering',
      'no_missions': 'No missions',
      'see_mission': 'See mission',
      'confirm': 'Confirm',
      'refuse': 'Refuse',
      'onboarding1_title': 'Join ARS.',
      'onboarding1_subtitle': 'A community committed to improving meals in healthcare settings.',
      'onboarding2_title': 'Train Yourself',
      'onboarding2_subtitle': 'Train at your own pace and be ready for your missions.',
      'onboarding3_title': 'Get paid',
      'onboarding3_subtitle': 'Work done, hours validated, payment guaranteed.',
      'agency_name': 'Agency of Catering & Health',
      'faq_title': 'FAQ',
      'faq_subtitle': 'Find answers to your frequent questions',
      'contact_title': 'Contact us',
      'contact_subtitle': 'A question? Our team is here to help you',
      'email_support_title': 'Email Support',
      'email_support_subtitle': 'Send us a message at any time',
      'phone_support_title': 'Phone Support',
      'phone_support_subtitle': 'Call our dedicated support line',
      'help_center': 'Help Center',
      'full_name': 'Full name',
      'name_hint': 'Enter your name',
      'email_hint': 'Enter your email',
      'subject': 'Subject',
      'subject_hint': 'Object of your message',
      'message': 'Message',
      'message_hint': 'Describe your request in detail...',
      'send_message': 'Send message',
      'category': 'Category',
      'gen_question': 'General question',
      'tech_prob': 'Technical problem',
      'billing': 'Billing',
      'other': 'Other',
      'message_sent': 'Message sent successfully!',
      'fill_form': 'Fill out the form below and we will get back to you as soon as possible.',
      'error_name': 'Please enter your name',
      'error_email': 'Please enter your email',
      'error_email_invalid': 'Invalid email',
      'error_subject': 'Please enter a subject',
      'error_message': 'Please enter your message',
      'faq_q1': 'How to accept a mission?',
      'faq_a1': 'To accept a mission, go to the "Missions" tab, browse available missions and click on the one that interests you. You can then view the details and click on "Accept mission".',
      'faq_q2': 'How to modify my personal information?',
      'faq_a2': 'Go to the "Profile" tab, then click on "Settings". You can modify your personal information, documents, and preferences there.',
      'faq_q3': 'What to do in case of a problem during a mission?',
      'faq_a3': 'In case of a problem, use the "Report an incident" button available on the detail page of your current mission. Our team will be alerted and will contact you quickly.',
      'faq_q4': 'How are my working hours calculated?',
      'faq_a4': 'Your working hours are automatically calculated based on the start and end times of the mission indicated. You can check your history in the "Completed Missions" tab.',
      'faq_q5': 'How to add a new document?',
      'faq_a5': 'In the "Profile" tab, "Documents" section, click on "+ Add a document". Select the file from your device (accepted formats: PDF, JPG, PNG).',
      'faq_q6': 'How to change the application language?',
      'faq_a6': 'Go to "Profile" > "Settings" > "Language". Select your preferred language from French, English, or Spanish, then click "Apply".',
      
      // Admin specific
      'our_mission': 'Our Mission',
      'mission_content': 'ARS\'s mission is to ensure the preparation, organization and execution of catering services within partner establishments, strictly respecting hygiene, safety and quality standards.',
      'legal_mentions': 'Legal Mentions',
      'legal_content': 'The missions carried out within the ARS platform comply with current legal obligations (HACCP, food safety).',
      'data_collection': 'Data Collection',
      'data_collection_content': 'We only collect data necessary for the proper functioning of our services (Identification, Contact Details, Missions).',
      'data_usage': 'Data Usage',
      'data_usage_content': 'Your data is used to ensure mission management, improve our services and respect our legal obligations.',
      'data_protection': 'Data Protection',
      'data_protection_content': 'We implement appropriate security measures (Encryption, Restricted access, Backups).',
      'your_rights': 'Your Rights',
      'your_rights_content': 'In accordance with GDPR, you have the rights to access, rectification, erasure and objection.',
      'share_message': 'Discover ARS App - The app for catering professionals!\n\nJoin our community of professional cooks!',
      'share_subject': 'ARS App - Application for catering professionals',
      'administration': 'Administration',
      'manage_resources': 'Manage platform resources',
      'monthly_stats': 'Monthly stats',
      'pros_active': 'Active pros',
      'satisfaction': 'Satisfaction',
      'prof_management': 'Professional management',
      'sites_management': 'Site management',
      'menus_management': 'Menu management',
      'recipes_management': 'Recipe management',
      'trainings_management': 'Training management',
      'team': 'Team',
      'see': 'See',
      'schedule': 'Schedule',
      'date': 'Date',
      'all_filter': 'All',
      'confirm_delete_mission': 'Are you sure you want to delete this mission at',
      'admin_panel': 'Admin',
      'modify_info': 'Modify information',
    },
    'es': {
      // General
      'hello': 'Hola',
      'back': 'Volver',
      'continue': 'Continuar',
      'apply': 'Aplicar',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'add': 'Añadir',
      'edit': 'Editar',
      'search': 'Buscar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      
      // Navigation
      'home': 'Inicio',
      'missions': 'Misiones',
      'training': 'Formación',
      'profile': 'Perfil',
      
      // Login
      'login': 'Iniciar sesión',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'no_account': '¿Aún no tienes cuenta?',
      'register': 'Registrarse',
      'register_link': 'Regístrate.',
      'login_instructions': 'Ingrese su correo electrónico y contraseña pour accéder à votre compte.',
      'error_password_short': 'La contraseña debe tener al menos 6 caracteres',
      'test_mode': 'Modo de Prueba',
      'choose_account_type': 'Elija el tipo de cuenta a probar:',
      'professional': 'Profesional',
      'client_establishment': 'Cliente (Establecimiento)',
      'admin': 'Admin',
      'get_started': 'Comenzar',
      'already_have_account': '¿Ya tienes una cuenta?',
      'forgot_password_desc': 'Ingrese su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
      'email_sent_title': '¡Email enviado!',
      'email_sent_desc1': 'Hemos enviado un enlace de restablecimiento a',
      'email_sent_desc2': 'Revise su bandeja de entrada y siga las instrucciones para restablecer su contraseña.',
      'send_link': 'Enviar enlace',
      'back_to_login': 'Volver al inicio de sesión',
      'resend_email': 'Reenviar email',
      'registration': 'Registro',
      'choose_profile': 'Elija Su Perfil',
      'choose_profile_desc': 'Para Ofrecerle Una Experiencia Personalizada, Indíquenos Su Perfil',
      'student_profile': 'Estudiante (Trabajador)',
      'student_profile_desc': 'Busco Formación, Alternancia, Empleo Estudiantil O Un Primer Empleo.',
      'recruiter_profile': 'Reclutador (Estructura)',
      'recruiter_profile_desc': 'Deseo Reclutar Pasantes, Alternantes O Jóvenes Graduados Para Mi Estructura.',
      'who_are_you': '¿Empieza por decirnos quién eres?',
      'who_are_you_desc': 'Esta información nos ayudará a conocerte mejor y a crear tu cuenta.',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'full_address': 'Dirección Completa',
      'phone_number': 'Número de teléfono',
      'next': 'SIGUIENTE',
      'login_back': 'Iniciar sesión',
      'documents_title': 'Sus documentos para validar su perfil',
      'documents_subtitle': 'Necesitamos algunas piezas para confirmar su identidad y calificaciones.',
      'id_card': 'Cédula de identidad *',
      'cv': 'Curriculum Vitae (CV) *',
      'diplomas': 'Diploma(s):',
      'no_file': 'Sin archivo',
      'error_file_pick': 'Error al seleccionar el archivo:',
      'journey_title': 'Cuéntanos tu trayectoria',
      'journey_subtitle': '¿Alguna vez has trabajado en cocina o en una estructura de salud? Cuéntanoslo todo.',
      'add_experience': 'Añadir una experiencia',
      'register_submit': 'REGISTRARSE',
      'professional_experience': 'Experiencia Profesional',
      'experience_hint': 'Ej: Cocinero en iTea',
      'start_date': 'Fecha de Inicio',
      'end_date': 'Fecha de Fin',
      'select_year_month': 'Seleccionar año y mes',
      'january': 'Enero', 'february': 'Febrero', 'march': 'Marzo', 'april': 'Abril',
      'may': 'Mayo', 'june': 'Junio', 'july': 'Julio', 'august': 'Agosto',
      'september': 'Septiembre', 'october': 'Octubre', 'november': 'Noviembre', 'december': 'Diciembre',
      
      // Home
      'mission_of_day': 'Misión del día',
      'upcoming_missions': 'Próximas misiones',
      'quick_access': 'Acceso rápido',
      'access_mission': 'Acceder a la misión',
      'incidents': 'Incidentes',
      'in_progress': 'En curso',
      
      // Missions
      'upcoming': 'Próximas',
      'completed': 'Completadas',
      'pending': 'Pendiente',
      'confirmed': 'Confirmado',
      'refused': 'Rechazado',
      'end_mission': 'Terminar misión',
      'report_incident': 'Reportar incidente',
      
      // Mission Detail
      'access_logistics': 'Acceso y Logística',
      'entry_code': 'Código de entrada',
      'kitchen_code': 'Código de cocina',
      'call_contact': 'Llamar al contacto',
      'menu_of_day': 'Menú del día',
      'see_recipe': 'Ver receta',
      'calculated_quantities': 'Cantidades calculadas',
      'residents': 'residentes',
      'daily_checklist': 'Lista de tareas diarias',
      
      // Training
      'mandatory': 'Obligatorias',
      'recommended': 'Recomendadas',
      'duration': 'Duración',
      'completed_status': 'Completado',
      'to_do': 'Por hacer',
      
      // Profile
      'documents': 'Documentos',
      'add_document': 'Añadir un documento',
      'settings': 'Ajustes',
      'logout': 'Cerrar sesión',
       'cv': 'Curriculum Vitae(CV)',
      'id_card': 'DNI',
      'diploma': 'Diploma de cocina',
      'cook_diploma': 'Diploma de cocina',
      'professional_cook': 'Cocinero profesional',
      'doc_added': 'Documento añadido',
      'doc_error': 'Error al añadir documento',
      'doc_opening': 'Abriendo',

      // Home & Dashboard
      'mission_today': 'Misión hoy',
      'available_professionals': 'Profesionales disponibles',
      'active_sites': 'Sitios activos',
      'create_mission': 'Crear misión',
      'create_training': 'Crear formación',
      'missions_of_day': 'Misiones del día',
      'see_all': 'Ver todo',
      'no_mission_available': 'No hay misiones disponibles',
      'all_missions': 'Todas las misiones',
      'recent_alerts': 'Alertas recientes',
      'incident_reported': 'Incidente reportado',
      'new_note': 'Nueva nota',
      'trainings_to_validate': 'formaciones por validar',
      'mission_management': 'Gestión de Misiones',
      'administration': 'Administración',
      'manage_resources': 'Gestione los recursos de la plataforma',
      'monthly_stats': 'Estadísticas del mes',
      'pros_active': 'Pros activos',
      'satisfaction': 'Satisfacción',
      'prof_management': 'Gestión de profesionales',
      'sites_management': 'Gestión de sitios',
      'menus_management': 'Gestión de menús',
      'recipes_management': 'Gestión de recetas',
      'trainings_management': 'Gestión de formaciones',
      'team': 'Equipo',
      'see': 'Ver',
      'schedule': 'Horario',
      'date': 'Fecha',
      'all_filter': 'Todos',
      'confirm_delete_mission': '¿Está seguro de que desea eliminar esta misión en',
      'admin_panel': 'Admin',
      'modify_info': 'Modificar información',
      'team_management': 'Gestión del equipo',
      'my_profile': 'Mi Perfil',
      'full_name': 'Nombre completo',
      'role': 'Rol',
      'admin_role': 'Administrador',
      'directrice_role': 'Directora',
      'chef_role': 'Jefe de cocina',
      'residents_stat': 'Residentes',
      'chefs_stat': 'Chefs',
      'information': 'Información',
      'address_label': 'Dirección',
      'phone_label': 'Teléfono',
      'capacity': 'Capacidad',
      'residents_count': 'residentes',
      'actions': 'Acciones',
      'send_feedback': 'Enviar comentarios',
      'report_incident_btn': 'Reportar un incidente',
      'your_satisfaction': 'Su satisfacción',
      'your_comment': 'Su comentario',
      'send_feedback_btn': 'Enviar comentarios',
      'today_label': 'Hoy',
      'tomorrow_label': 'Mañana',
      'planned': 'Planificada',
      'starter': 'Entrante',
      'main_course': 'Plato principal',
      'side_dish': 'Acompañamiento',
      'dessert': 'Postre',
      'menu_upper': 'MENÚ',
      'see_details': 'Ver detalles',
      'edit_info': 'Editar información',
      'change_password': 'Cambiar contraseña',
      
      // Search & Filters
      'search_mission_hint': 'Buscar una misión...',
      'search_professional_hint': 'Buscar un profesional...',
      'search_no_results': 'Búsqueda no encontrada',
      'search_no_results_desc': 'Ninguna misión coincide con su búsqueda',
      'no_professional_found': 'No se encontró ningún profesional',
      'filters': 'Filtros',
      'today': 'Hoy',
      'this_week': 'Esta semana',
      'all_filter': 'Todo',

      // Actions & Dialogs
      'delete_mission_title': 'Eliminar misión',
      'delete_mission_confirm': '¿Está seguro de que desea eliminar esta misión?',
      'mission_deleted': 'Misión eliminada',
      'mission_label': 'Misión:',
      'available': 'Disponibles',
      
      // Settings
      'language': 'Idioma',
      'about': 'Acerca de ARS',
      'privacy': 'Política de privacidad',
      'help_support': 'Ayuda y Soporte',
      'share_app': 'Compartir aplicación',
      'language_changed': 'Idioma cambiado a',
      
      // Registration Steps
      'step': 'Paso',
      'personal_info': 'Información personal',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'phone': 'Teléfono',
      'date_of_birth': 'Fecha de nacimiento',
      'address': 'Dirección',
      'postal_code': 'Código postal',
      'city': 'Ciudad',
      'professional_experience': 'Experiencia profesional',
      'main_function': 'Función principal',
      'years_experience': 'Años de experiencia',
      'specialties': 'Especialidades',
      'select_function': 'Seleccione su función',
      'select_experience': 'Seleccione',
      'required_documents': 'Documentos requeridos',
      'profile_photo': 'Foto de perfil',
      'cooking_diplomas': 'Diplomas de cocina',
      'medical_certificate': 'Certificado médico',
      'driving_license': 'Licencia de conducir',
      'create_password': 'Crear contraseña',
      'confirm_password': 'Confirmar contraseña',
      'accept_terms': 'Acepto los términos y condiciones',
      
      // Specialties
      'french_cuisine': 'Cocina francesa',
      'italian_cuisine': 'Cocina italiana',
      'asian_cuisine': 'Cocina asiática',
      'pastry': 'Pastelería',
      'vegetarian': 'Cocina vegetariana',
      'collective': 'Cocina colectiva',
      'no_missions': 'No hay misiones',
      'see_mission': 'Ver misión',
      'confirm': 'Confirmar',
      'refuse': 'Rechazar',
      'onboarding1_title': 'Únete a ARS.',
      'onboarding1_subtitle': 'Una comunidad comprometida con la mejora de las comidas en entornos sanitarios.',
      'onboarding2_title': 'Fórmate',
      'onboarding2_subtitle': 'Fórmate a tu ritmo et prepárate para tus misiones.',
      'onboarding3_title': 'Recibe tu pago',
      'onboarding3_subtitle': 'Trabajo realizado, horas validadas, pago garantizado.',
      'agency_name': 'Agencia de Restauración y Salud',
      'faq_title': 'FAQ',
      'faq_subtitle': 'Encuentre respuestas a sus preguntas frecuentes',
      'contact_title': 'Contáctenos',
      'contact_subtitle': '¿Una pregunta? Nuestro equipo está aquí para ayudarle',
      'email_support_title': 'Soporte por Email',
      'email_support_subtitle': 'Envíenos un mensaje en cualquier momento',
      'phone_support_title': 'Soporte Telefónico',
      'phone_support_subtitle': 'Llame a nuestra línea de asistencia dedicada',
      'help_center': 'Centro de Ayuda',
      'full_name': 'Nombre completo',
      'name_hint': 'Ingrese su nombre',
      'email_hint': 'Ingrese su correo electrónico',
      'subject': 'Asunto',
      'subject_hint': 'Objeto de su mensaje',
      'message': 'Mensaje',
      'message_hint': 'Describa su solicitud en detalle...',
      'send_message': 'Enviar mensaje',
      'category': 'Categoría',
      'gen_question': 'Pregunta general',
      'tech_prob': 'Problema técnico',
      'billing': 'Facturación',
      'other': 'Otro',
      'message_sent': '¡Mensaje enviado con éxito!',
      'fill_form': 'Complete el formulario a continuación y le responderemos lo antes posible.',
      'error_name': 'Por favor ingrese su nombre',
      'error_email': 'Por favor ingrese su correo electrónico',
      'error_email_invalid': 'Correo electrónico inválido',
      'error_subject': 'Por favor ingrese un asunto',
      'error_message': 'Por favor ingrese su mensaje',
      'faq_q1': '¿Cómo aceptar una misión?',
      'faq_a1': 'Para aceptar una misión, vaya a la pestaña "Misiones", consulte las misiones disponibles y haga clic en la que le interese. Luego podrá ver los detalles y hacer clic en "Aceptar misión".',
      'faq_q2': '¿Cómo modificar mi información personal?',
      'faq_a2': 'Vaya a la pestaña "Perfil", luego haga clic en "Configuraciones". Allí podrá modificar su información personal, sus documentos y sus preferencias.',
      'faq_q3': '¿Qué hacer en caso de un problema durante una misión?',
      'faq_a3': 'En caso de un problema, use el botón "Informar un incidente" disponible en la página de detalles de su misión actual. Nuestro equipo será alertado y se comunicará con usted rápidamente.',
      'faq_q4': '¿Cómo se calculan mis horas de trabajo?',
      'faq_a4': 'Sus horas de trabajo se calculan automáticamente a partir de las horas de inicio y fin de la misión indicadas. Puede consultar su historial en la pestaña "Misiones completadas".',
      'faq_q5': '¿Cómo añadir un nuevo documento?',
      'faq_a5': 'En la pestaña "Perfil", sección "Documentos", haga clic en "+ Añadir un documento". Seleccione el archivo desde su dispositivo (formatos aceptados: PDF, JPG, PNG).',
      'faq_q6': '¿Cómo cambiar el idioma de la aplicación?',
      'faq_a6': 'Vaya a "Perfil" > "Configuraciones" > "Idioma". Seleccione su idioma preferido entre francés, inglés o español, luego haga clic en "Aplicar".',
      
      // Admin specific
      'our_mission': 'Nuestra Misión',
      'mission_content': 'La misión de ARS es asegurar la preparación, organización y ejecución de los servicios de restauración en los establecimientos asociados, respetando estrictamente las normas de higiene, seguridad y calidad.',
      'legal_mentions': 'Menciones Legales',
      'legal_content': 'Las misiones realizadas dentro de la plataforma ARS cumplen con las obligaciones legales vigentes (HACCP, seguridad alimentaria).',
      'data_collection': 'Recopilación de datos',
      'data_collection_content': 'Solo recopilamos los datos necesarios para el buen funcionamiento de nuestros servicios (Identificación, Contacto, Misiones).',
      'data_usage': 'Uso de los datos',
      'data_usage_content': 'Sus datos se utilizan para garantizar la gestión de las misiones, mejorar nuestros servicios y cumplir con nuestras obligaciones legales.',
      'data_protection': 'Protección de datos',
      'data_protection_content': 'Implementamos medidas de seguridad adecuadas (Cifrado, Acceso restringido, Copias de seguridad).',
      'your_rights': 'Sus derechos',
      'your_rights_content': 'De acuerdo con el RGPD, usted tiene los derechos de acceso, rectificación, eliminación y oposición.',
      'share_message': '¡Descubre ARS App - La aplicación para profesionales de la restauración!\n\n¡Únete a nuestra comunidad de cocineros profesionales!',
      'share_subject': 'ARS App - Aplicación para profesionales de la restauración',
    },
  };
}



















